Integration Of SOMEIP dissection to Network Trace
tracecompass/tracecompass pull request #1
Opened 2018-09-19 09:56 UTC by Prasanna-Vadanan

Added a new protocol to the Network Trace feature of Trace Compass

2018-09-19 14:29 UTC, tahini requested changes
Thank you for this pull request. I did a basic review, mostly of copyright stuff.

But the github repository is only a mirror of the official Trace Compass repository and it is not where we review and accept patches. Here are the instructions to submit patches through Eclipse's gerrit: https://wiki.eclipse.org/Trace_Compass/Contributor_Guidelines

You should squash your commits into 1 and push it on gerrit as per instructions above. We will do a more thorough review once on gerrit.

Also please provide a trace, that you can add in the unit test plugin so we can test the new protocol. That would help review the patch.

2018-09-19 14:29 UTC, tahini commented on pcap/org.eclipse.tracecompass.pcap.core/src/org/eclipse/tracecompass/internal/pcap/core/protocol/someip_service_discovery/SOMEIP_SDEndpoint.java
> + * Copyright (c) 2014 Ericsson
Careful with copyright headers, this should be your organization and 2018

2018-09-19 14:29 UTC, tahini commented on pcap/org.eclipse.tracecompass.pcap.core/src/org/eclipse/tracecompass/internal/pcap/core/protocol/someip_service_discovery/SOMEIP_SDEndpoint.java
> + * @author Vincent Perot
And here you should have your name

2018-09-19 14:29 UTC, tahini commented on pcap/org.eclipse.tracecompass.tmf.pcap.core/src/org/eclipse/tracecompass/internal/tmf/pcap/core/protocol/TmfPcapProtocol.java
> +    UNKNOWN(PcapProtocol.UNKNOWN),
Leave unknown as the last one

2018-09-19 14:29 UTC, tahini commented on pcap/org.eclipse.tracecompass.tmf.pcap.core/src/org/eclipse/tracecompass/internal/tmf/pcap/core/util/ProtocolConversion.java
> + *
Do not remove copyright headers from these files, you can put 2014, 2018 Ericsson, your organization

2018-09-20 13:02 UTC, TheMatthew commented
Hey, I would like to counter, please push the branch as-is to gerrit, it should be easier to commit. I like the raviolitude of the patches. ;)

2018-09-26 23:40 UTC, TheMatthew commented
Went through the entire patchset... I agree with Genevieve, the whole branch chain should be squashed as it does not compile in some parts.

2024-03-20 14:57 UTC, bhufmann commented
Closing this one. This mirror will be archived. If PR is still relevant please contribute it to: https://github.com/eclipse-tracecompass/org.eclipse.tracecompass. Thanks!

2024-03-20 14:57 UTC, closed without merging